crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("crudapp.urls")),
]

crudapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('emp', views.emp),
    path('', views.boot),
    path('show/',views.show, name = 'show'),
    path('signup', views.register_user),
    path('login/', views.login_user, name = 'login'),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy),
    path('logout/', views.logout_user, name='logout'),

]

crudapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from django.db import models
class Employee(models.Model):
    eid = models.CharField(max_length=20)
    ename = models.CharField(max_length=100)
    eemail = models.EmailField()
    econtact = models.CharField(max_length=15)
    class Meta:
        db_table = "employee"

crudapp/forms.py
from django import forms
from .models import Employee
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"

crudapp/views.py
from django.shortcuts import render, redirect
from .models import Employee
from .forms import EmployeeForm,CreateUserForm
from django.contrib import messages #import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .decorators import unauthenticated_user
# Create your views here.
@login_required(login_url='login')
def emp(request):
    # if request.method=='POST':
    form=EmployeeForm(request.POST)
    if form.is_valid():
        form.save()
        messages.success(request, "user added.")
        return redirect('/show')
    return render(request,'index.html',{'form':form})
@login_required(login_url='login')
def show(request):
    employees =Employee.objects.all()
    return render(request, 'show.html', {'employees': employees })
@login_required(login_url='login')
def boot(request):
    return render(request, 'home.html')
@login_required(login_url='login')
def destroy(request,id):
    employees =Employee.objects.get(id=id)
    employees.delete()
    messages.warning(request, "user deleted.")
    return redirect('/show')
@login_required(login_url='login')
def edit(request,id):
    employee=Employee.objects.get(id=id)
    messages.warning(request, "user edited.")
    return render(request,'edit.html',{'employee':employee})
@login_required(login_url='login')
def update(request,id):
    employee=Employee.objects.get(id=id)
    form=EmployeeForm(request.POST,instance=employee)
    if form.is_valid():
        form.save()
        return redirect('/show')
    return render(request,'edit.html',{'employee':employee})

def login_user(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.info(request, f'{username}, You are logged in.')
            return redirect("/")
        else:
            messages.info(request, 'Wrong passwrod or username')
            return redirect('login')
    return render(request, 'login.html')

def register_user(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, 'Account is created.')
            return redirect('login/')
        else:
            context = {'form': form}
            messages.info(request, 'Invalid credentials')
            return render(request, 'signup.html', context)

    context = {'form': form}
    return render(request, 'signup.html', context)

@login_required(login_url='login')
def logout_user(request):
    logout(request)
    messages.info(request, 'You logged out successfully')
    return redirect('login')
# def emp(request):
#     if request.method == "POST":
#         form = EmployeeForm(request.POST)
#         if form.is_valid():
#             try:
#                 form.save()
#                 return redirect('/show')
#             except:
#                 pass
#     else:
#         form = EmployeeForm()
#     return render(request,'index.html',{'form':form})

crudapp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, Umer!</title>
  </head>
  <body>
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About Us</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/show">Show</a>

          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>

    </ul>
            <a href="{% url 'login' %}" class="logo"></a>
                <a class="profile-icon-link-container" href="{% url 'logout' %}">
                    <div class="header-logout">Logout</div>
                </a>

  </div>
</nav>
{% block body %} {% endblock body %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

crudapp/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>

</head>
<body>
<form method="POST" class="post-form" action="/update/{{employee.id}}">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Id:</label>
    <div class="col-sm-4">
        <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Name:</label>
    <div class="col-sm-4">
        <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Email:</label>
    <div class="col-sm-4">
        <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ employee.eemail }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Contact:</label>
    <div class="col-sm-4">
        <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-success">Update</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>
{% endblock body %}

crudapp/templates/home.html
{% extends 'base.html' %}
{% block body %}
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
           <img src="https://source.unsplash.com/1200x900/?uncle,water" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
           <img src="https://source.unsplash.com/1200x900/?uncle,water" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
           <img src="https://source.unsplash.com/1200x900/?uncle,water" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<div>
    <div class="card-group">
  <div class="card">
        <img src="https://source.unsplash.com/1200x900/?nature,water" class="d-block w-100" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
  <div class="card">
        <img src="https://source.unsplash.com/1200x900/?nature,water" class="d-block w-100" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
  <div class="card">
        <img src="https://source.unsplash.com/1200x900/?nature,water" class="d-block w-100" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
</div>
</div>
{% endblock body %}

crudapp/templates/index.html
{% extends 'base.html' %}
{% block body %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>

</head>
<body>
<form method="POST" class="post-form" action="/emp">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Enter Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Id:</label>
    <div class="col-sm-4">
      {{ form.eid }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Name:</label>
    <div class="col-sm-4">
      {{ form.ename }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Email:</label>
    <div class="col-sm-4">
      {{ form.eemail }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Contact:</label>
    <div class="col-sm-4">
      {{ form.econtact }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>
{% endblock body %}

crudapp/templates/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">




    <title>Login Page</title>
  </head>
  <body>

  <header>
      <nav class="navbar">
      </nav>
  </header>

  {% if messages %}
    <div class="notification-container">
        <div class="notification">
            {% for message in messages %}
            <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
        </div>
    </div>
    <script>
        var cross = document.getElementById('cross')
        cross.addEventListener('click', ()=> {
            document.getElementsByClassName('notification-container')[0].style.display = 'none';
        })
    </script>
    {% endif %}


    <main class="main-container">
        <div class="container ">
          <h1 class="signup-heading">Log in</h1>
            <div class="user-content-container user-profile-form-container">
              <form action="" method="POST">
                {% csrf_token %}
                  <ul>
                  <li class="name">
                      <label for="username">Username</label>
                      <input type="text" name="username" id="username" class="username-input" placeholder="Username">
                  </li>

                  <li class="pass">
                    <label for="">Password</label>
                    <input type="password" name = "password" id="password" class="pass-input" placeholder="Password">
                  </li>

                    <button class="signup-button"> Log in </button>
                  </ul>
              </form>

            </div>
        </div>
    </main>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="undefined" crossorigin="anonymous"></script>
  </body>
</html>

crudapp/templates/show.html
{% extends 'base.html' %}
{% block body %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employee Records</title>

</head>
<body>
<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="True">&times;</span>
    </button>
    {{ message }}
  </div>
</div>
{% endfor %}
<!-- {% if messages %}-->
<!--    <div class="notification-container">-->
<!--        <div class="notification">-->
<!--            {% for message in messages %}-->
<!--            <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}-->
<!--                 <button type="button" class="close" data-dismiss="alert" aria-label="Close">-->
<!--      <span aria-hidden="True">&times;</span>-->
<!--    </button></p>-->

<!--            {% endfor %}-->
<!--        </div>-->
<!--    </div>-->
<!--{% endif  %}-->
<!--{% if messages %}-->
<!--<ul class="messages">-->
<!--    {% for message in messages %}-->
<!--    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>-->
<!--        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}-->
<!--            <button type="button" class="close" data-dismiss="alert" aria-label="Close">-->
<!--      <span aria-hidden="True">&times;</span>-->
<!--    </button>-->
<!--        {{ message }}-->
<!--    </li>-->
<!--    {% endfor %}-->
<!--</ul>-->
<!--{% endif %}-->
    <tr>
        <th>Employee ID</th>
        <th>Employee Name</th>
        <th>Employee Email</th>
        <th>Employee Contact</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
{% for employee in employees %}
    <tr>
        <td>{{ employee.eid }}</td>
        <td>{{ employee.ename }}</td>
        <td>{{ employee.eemail }}</td>
        <td>{{ employee.econtact }}</td>
        <td>
            <a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
            <a href="/delete/{{ employee.id }}">Delete</a>
        </td>
    </tr>
{% endfor %}
    </tbody>
</table>
<br>
<br>
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>
</body>
</html>
{% endblock body %}

crudapp/templates/signup.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">



    <title>Regiser Page</title>
  </head>
  <body>

<!---->


    {% if messages %}
    <div class="notification-container">
        <div class="notification">
            {% for message in messages %}
            <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
        </div>
    </div>
    <script>
        var cross = document.getElementById('cross')
        cross.addEventListener('click', ()=> {
            document.getElementsByClassName('notification-container')[0].style.display = 'none';
        })
    </script>
    {% endif %}


  <main class="main-container">
      <div class="container ">
        <h1 class="signup-heading">Sign Up</h1>
        <div class="user-content-container user-profile-form-container">
          <form action="" method="POST">
            {% csrf_token %}
            <ul>
              <li class="name">
                  <label for="username">Username</label>
                  {{form.username.errors}}
                  {{form.username}}
              </li>

              <li class="email">
                <label for="">Email</label>
                {{form.email.errors}}
                {{form.email}}
              </li>

              <li class="pass">
                <label for="">Password</label>
                {{form.password1.errors}}
                {{form.password1}}
              </li>

              <li class="confirm-pass">
                <label for="">Confirm Password</label>
                {{form.password2.errors}}
                {{form.password2}}
              </li>
          </ul>

          <button class="signup-button">Sign up</button>

      </div>
      </div>
  </main>

<script>
  var id_username = document.getElementById('id_username')
  var id_email = document.getElementById('id_email')
  var id_password1 = document.getElementById('id_password1')
  var id_password2 = document.getElementById('id_password2')

  id_username.placeholder = 'Username';
  id_email.placeholder = 'Email';
  id_password1.placeholder = 'Password';
  id_password2.placeholder = 'Confirm password';

</script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="undefined" crossorigin="anonymous"></script>

</body>
</html>